#############################################################################
# Makefile for building: BiblioApp
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sat May 18 14:54:36 2013
# Project:  ../bibli-organizer/BiblioApp.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ../bibli-organizer/BiblioApp.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I../bibli-organizer -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I../bibli-organizer -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../bibli-organizer/main.cpp \
		../bibli-organizer/mainwindow.cpp \
		../bibli-organizer/livre.cpp \
		../bibli-organizer/biblio.cpp \
		../bibli-organizer/tinyxml/tinyxml.cpp \
		../bibli-organizer/tinyxml/tinystr.cpp \
		../bibli-organizer/tinyxml/tinyxmlerror.cpp \
		../bibli-organizer/tinyxml/tinyxmlparser.cpp \
		../bibli-organizer/dossier.cpp \
		../bibli-organizer/fichelivre.cpp \
		../bibli-organizer/itemindex.cpp \
		../bibli-organizer/pilealire.cpp moc_mainwindow.cpp \
		moc_fichelivre.cpp \
		moc_pilealire.cpp
OBJECTS       = main.o \
		mainwindow.o \
		livre.o \
		biblio.o \
		tinyxml.o \
		tinystr.o \
		tinyxmlerror.o \
		tinyxmlparser.o \
		dossier.o \
		fichelivre.o \
		itemindex.o \
		pilealire.o \
		moc_mainwindow.o \
		moc_fichelivre.o \
		moc_pilealire.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		../bibli-organizer/BiblioApp.pro
QMAKE_TARGET  = BiblioApp
DESTDIR       = 
TARGET        = BiblioApp

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../bibli-organizer/BiblioApp.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ../bibli-organizer/BiblioApp.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ../bibli-organizer/BiblioApp.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/BiblioApp1.0.0 || $(MKDIR) .tmp/BiblioApp1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/BiblioApp1.0.0/ && $(COPY_FILE) --parents ../bibli-organizer/mainwindow.h ../bibli-organizer/livre.h ../bibli-organizer/biblio.h ../bibli-organizer/tinyxml/tinyxml.h ../bibli-organizer/tinyxml/tinystr.h ../bibli-organizer/dossier.h ../bibli-organizer/fichelivre.h ../bibli-organizer/itemindex.h ../bibli-organizer/pilealire.h .tmp/BiblioApp1.0.0/ && $(COPY_FILE) --parents ../bibli-organizer/main.cpp ../bibli-organizer/mainwindow.cpp ../bibli-organizer/livre.cpp ../bibli-organizer/biblio.cpp ../bibli-organizer/tinyxml/tinyxml.cpp ../bibli-organizer/tinyxml/tinystr.cpp ../bibli-organizer/tinyxml/tinyxmlerror.cpp ../bibli-organizer/tinyxml/tinyxmlparser.cpp ../bibli-organizer/dossier.cpp ../bibli-organizer/fichelivre.cpp ../bibli-organizer/itemindex.cpp ../bibli-organizer/pilealire.cpp .tmp/BiblioApp1.0.0/ && $(COPY_FILE) --parents ../bibli-organizer/mainwindow.ui .tmp/BiblioApp1.0.0/ && (cd `dirname .tmp/BiblioApp1.0.0` && $(TAR) BiblioApp1.0.0.tar BiblioApp1.0.0 && $(COMPRESS) BiblioApp1.0.0.tar) && $(MOVE) `dirname .tmp/BiblioApp1.0.0`/BiblioApp1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/BiblioApp1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_fichelivre.cpp moc_pilealire.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_fichelivre.cpp moc_pilealire.cpp
moc_mainwindow.cpp: ../bibli-organizer/fichelivre.h \
		../bibli-organizer/livre.h \
		../bibli-organizer/dossier.h \
		../bibli-organizer/itemindex.h \
		../bibli-organizer/biblio.h \
		../bibli-organizer/tinyxml/tinyxml.h \
		../bibli-organizer/tinyxml/tinystr.h \
		../bibli-organizer/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../bibli-organizer/mainwindow.h -o moc_mainwindow.cpp

moc_fichelivre.cpp: ../bibli-organizer/livre.h \
		../bibli-organizer/fichelivre.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../bibli-organizer/fichelivre.h -o moc_fichelivre.cpp

moc_pilealire.cpp: ../bibli-organizer/pilealire.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../bibli-organizer/pilealire.h -o moc_pilealire.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ../bibli-organizer/mainwindow.ui
	/usr/bin/uic-qt4 ../bibli-organizer/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../bibli-organizer/main.cpp ../bibli-organizer/mainwindow.h \
		../bibli-organizer/fichelivre.h \
		../bibli-organizer/livre.h \
		../bibli-organizer/dossier.h \
		../bibli-organizer/itemindex.h \
		../bibli-organizer/biblio.h \
		../bibli-organizer/tinyxml/tinyxml.h \
		../bibli-organizer/tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../bibli-organizer/main.cpp

mainwindow.o: ../bibli-organizer/mainwindow.cpp ../bibli-organizer/mainwindow.h \
		../bibli-organizer/fichelivre.h \
		../bibli-organizer/livre.h \
		../bibli-organizer/dossier.h \
		../bibli-organizer/itemindex.h \
		../bibli-organizer/biblio.h \
		../bibli-organizer/tinyxml/tinyxml.h \
		../bibli-organizer/tinyxml/tinystr.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../bibli-organizer/mainwindow.cpp

livre.o: ../bibli-organizer/livre.cpp ../bibli-organizer/livre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o livre.o ../bibli-organizer/livre.cpp

biblio.o: ../bibli-organizer/biblio.cpp ../bibli-organizer/biblio.h \
		../bibli-organizer/dossier.h \
		../bibli-organizer/livre.h \
		../bibli-organizer/tinyxml/tinyxml.h \
		../bibli-organizer/tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o biblio.o ../bibli-organizer/biblio.cpp

tinyxml.o: ../bibli-organizer/tinyxml/tinyxml.cpp ../bibli-organizer/tinyxml/tinyxml.h \
		../bibli-organizer/tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxml.o ../bibli-organizer/tinyxml/tinyxml.cpp

tinystr.o: ../bibli-organizer/tinyxml/tinystr.cpp ../bibli-organizer/tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinystr.o ../bibli-organizer/tinyxml/tinystr.cpp

tinyxmlerror.o: ../bibli-organizer/tinyxml/tinyxmlerror.cpp ../bibli-organizer/tinyxml/tinyxml.h \
		../bibli-organizer/tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxmlerror.o ../bibli-organizer/tinyxml/tinyxmlerror.cpp

tinyxmlparser.o: ../bibli-organizer/tinyxml/tinyxmlparser.cpp ../bibli-organizer/tinyxml/tinyxml.h \
		../bibli-organizer/tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxmlparser.o ../bibli-organizer/tinyxml/tinyxmlparser.cpp

dossier.o: ../bibli-organizer/dossier.cpp ../bibli-organizer/dossier.h \
		../bibli-organizer/livre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dossier.o ../bibli-organizer/dossier.cpp

fichelivre.o: ../bibli-organizer/fichelivre.cpp ../bibli-organizer/fichelivre.h \
		../bibli-organizer/livre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fichelivre.o ../bibli-organizer/fichelivre.cpp

itemindex.o: ../bibli-organizer/itemindex.cpp ../bibli-organizer/itemindex.h \
		../bibli-organizer/livre.h \
		../bibli-organizer/dossier.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o itemindex.o ../bibli-organizer/itemindex.cpp

pilealire.o: ../bibli-organizer/pilealire.cpp ../bibli-organizer/pilealire.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pilealire.o ../bibli-organizer/pilealire.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_fichelivre.o: moc_fichelivre.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fichelivre.o moc_fichelivre.cpp

moc_pilealire.o: moc_pilealire.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pilealire.o moc_pilealire.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

